config/routes.rb
Soxform::Application.routes.draw do
  resources :forms
  root :to => 'calendar#index'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :printable_sox_form

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  attr_accessible :details, :finance_approval, :fund_source, :glwbsaction, :inventory, :method_of_payment, :total_budget

  belongs_to :form

end

app/models/form.rb
class Form < ActiveRecord::Base
  attr_accessible :actions, :brand, :budget, :comments, :end_at, :kpi, :lar, :mechanism, :par, :name, :rationale, :sox_number, :start_at, :status,
  :targeted_stores, :tobacco_class, :province, :printable_sox_form, :program_types_attributes, :lar1, :lar2, :lar3,
  :material, :budget_attributes, :par_results_attributes, :key_performance_indicators_attributes, :par_requirement, :lar_requirement

  

  has_event_calendar

	BO_CLASS = ["Toys", "Models", "Other"]
	BO_PR = ["BC","AB","MB","SK","ON","QC","NB","NS","NF","PEI"]
	FORM_STATUS = ["Approved", "In Progress", "Cancelled"]

	has_one :budget
	has_many :program_types
	has_many :key_performance_indicators
	has_attached_file :printable_sox_form
	has_many :par_results
		accepts_nested_attributes_for :key_performance_indicators
	accepts_nested_attributes_for :par_results
	accepts_nested_attributes_for :program_types
	accepts_nested_attributes_for :budget

end

app/models/key_performance_indicator.rb
class KeyPerformanceIndicator < ActiveRecord::Base
  attr_accessible :form_id, :kpi, :kpi_followup

  belongs_to :form
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :form_id, :par_order_id
  
end

app/models/par_result.rb
class ParResult < ActiveRecord::Base
  attr_accessible :comments, :form_id, :incremental_cartons, :incremental_margin, :lift_percent, :par_version, :par_link,
  :overall_score, :roi, :spend

  belongs_to :form

end

app/models/program_type.rb
class ProgramType < ActiveRecord::Base
  attr_accessible :form_id, :name, :task

  belongs_to :form
end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :name

  has_many :province_forms
  has_many :forms, through: :province_forms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Form.event_strips_for_month(@shown_month)
  end
  
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  # GET /forms
  # GET /forms.json
  def index


    @forms = Form.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forms }
    end
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
    @form = Form.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @form }
    end
  end

  # GET /forms/new
  # GET /forms/new.json
  def new
    @form = Form.new
   

    1.times {@form.program_types.build}
    1.times {@form.key_performance_indicators.build}

    @budget = @form.build_budget(params[:budget])


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @form }
    end
  end

  # GET /forms/1/edit
  def edit
    @form = Form.find(params[:id])
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(params[:form])

    respond_to do |format|
      if @form.save
        
        format.html { redirect_to @form, notice: 'SOX Form was successfully created.' }
        format.json { render json: @form, status: :created, location: @form }
      else
        format.html { render action: "new" }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forms/1
  # PUT /forms/1.json
  def update
    @form = Form.find(params[:id])

    respond_to do |format|
      if @form.update_attributes(params[:form])
        format.html { redirect_to @form, notice: 'SOX Form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form = Form.find(params[:id])
    @form.destroy

    respond_to do |format|
      format.html { redirect_to forms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/forms/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/forms_helper.rb
module FormsHelper


end

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "application" %>

<h1>Calendar</h1>

<%= raw(event_calendar) %>

app/views/forms/_budget_fields.html.erb
<div class="nested-fields">

<h3> 3. Budget Breakdown </h3>

<%= f.input :total_budget %>
<%= f.input :details, input_html: {style: 'height:300px;', class: 'span7'}, as: :text  %>
<%= f.input :finance_approval, inline_label: 'Require Approval from Finance' %>
<%= f.input :fund_source, label: 'Source of funds' %>
<%= f.input :glwbsaction, label: 'GL, WBS, Action Details', input_html: {style: 'height:200px;', class: 'span7'}, as: :text %>

<h3> 4. Method of Payment </h3>
<%= f.input :method_of_payment, label: 'Details', input_html: {style: 'height:150px;', class: 'span7'}, as: :text %>

<h3> 5. Additional Inventory Requirements </h3>

<%= f.input :inventory, label: 'Details', input_html: {style: 'height:150px;', class: 'span7'}, as: :text %>


</div>

  

app/views/forms/_execution_fields.html.erb
<div class="nested-fields">

   <%= f.input :name %>
   <%= link_to_remove_association "Remove Program Type", f %>

    <%= link_to_add_association "Add Program Tasks", f, :program_tasks, :class => "btn btn-primary" %> 

</div>

app/views/forms/_form.html.erb
<link rel="staylesheet" href="css/bootstrap.min.css"/>
<script src="js/jquery-1.9.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<script>
  $(function () {
    $('#tabs a:first').tab('show')
  })


</script>


<%= simple_form_for(@form, :html => {:class => "form-horizontal" }) do |f| %>

<%= f.input :name,  input_html: { class: 'span7' }, label: 'Program Name'  %>

<div class="form-inputs.row">
  <%= f.input :sox_number, label: 'SOX Number', :wrapper_html => { :class => 'span2' }%>
     <%= f.input :start_at, :as => :datepicker, :wrapper_html => { :class => 'span2' } %>
      <%= f.input :end_at, :as => :datepicker, :wrapper_html => { :class => 'span2' }  %>
      <%= f.input :status, :collection => Form::FORM_STATUS, :wrapper_html => { :class => 'span6' } %>
</div>

<ul class="nav nav-tabs" id="tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Program Overview</a></li>
    <li><a href="#tab2" data-toggle="tab">Execution</a></li>
    <li><a href="#tab3" data-toggle="tab">Finance and Operations</a></li>
    <li><a href="#tab4" data-toggle="tab">KPI</a></li>
    <li><a href="#tab5" data-toggle="tab">Follow Up Requirements</a></li>
    <li><a href="#tab6" data-toggle="tab">PAR Upload</a></li>
    <li><a href="#tab7" data-toggle="tab">LAR Upload</a></li>
</ul>


<div class="tab-content">



  <div class="tab-pane active" id="tab1">

  <h3> Program Overview </h3>

  <%= f.input :province, :collection => Form::BO_PR , :as => :check_boxes,  :wrapper_html => { :style => 'display: inline' }%>
  <%= f.input :tobacco_class, :collection => Form::BO_CLASS, :as => :radio_buttons, item_wrapper_class: 'inline', label: 'Product Type'  %>
  <%= f.input :brand %>
  <%= f.input :targeted_stores %>
  <%= f.input :printable_sox_form, label: 'Upload Target List' , input_html: {accept: ('application/pdf') },:class => 'btn-primary'  %>
  <%= f.input :rationale %>

  </div>



  <div class="tab-pane" id="tab2">

    <h3> 1. The Strategic Plan and Execution </h3>

    <%= f.simple_fields_for :program_types do |program_type| %>
    <%= render 'program_type_fields', :f => program_type %>

    <%= link_to_add_association "Add Program Type", f, :program_types, :data => {"association-insertion-node" => "this" }  %>
        <% end %>

    <h3> 2. POS Material / Material Communication </h3>
    <%= f.input :material, input_html: {style: 'height:300px;', class: 'span7'}, as: :text  %>



 </div>

  <div class="tab-pane" id="tab3">

    <%= f.simple_fields_for :budget do |budget| %>
     <%= render 'budget_fields', :f => budget %>
           <% end %>
   </div>


  <div class="tab-pane" id="tab4">


  <h3> 6. KPI </h3>


    <%= f.simple_fields_for :key_performance_indicators do |key_performance_indicator| %>
    <%= render 'key_performance_indicator_fields', :f => key_performance_indicator %>
    <% end %>

      <%= link_to_add_association "Add KPI", f, :key_performance_indicators, :data => {"association-insertion-node" => "this" } %>
   </div>



  <div class="tab-pane" id="tab5">


  <h3> 7. Requirements </h3>

  <%= f.input :par_requirement, inline_label: 'PAR Required' %>
  <%= f.input :par, label: 'PAR Details', input_html: {style: 'height:150px;', class: 'span7'}, as: :text %>
  <%= f.input :lar_requirement, inline_label: 'LAR Required' %>
  <%= f.input :lar, label: 'LAR Details', input_html: {style: 'height:150px;', class: 'span7'}, as: :text %>


   </div>

  <div class="tab-pane" id="tab6">


    <%= f.simple_fields_for :par_results do |par_result| %>
    <%= render 'par_result_fields', :f => par_result %>

       <% end %>
    <%= link_to_add_association "Add PAR", f, :par_results, :data => {"association-insertion-node" => "this" } %>




   </div>

  <div class="tab-pane" id="tab7">

  <%= f.input :lar1, label: 'LAR #1 Link', input_html: {class: 'span7'}%>
  <%= f.input :lar2, label: 'LAR #2 Link', input_html: {class: 'span7'}%>
  <%= f.input :lar3, label: 'LAR #3 Link', input_html: {class: 'span7'}%>


   </div>

</div>



  </br><%= f.button :submit, :class => 'btn-primary' %>
  <%= f.button :submit, :class => 'btn-primary'
  submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>

<% end %>

app/views/forms/_key_performance_indicator_fields.html.erb
<div class="nested-fields">


<%= f.input :kpi, input_html: {class: 'span7'} %>
<%= f.input :kpi_followup %>


<%= link_to_remove_association "Remove KPI", f %>

</div>

  

app/views/forms/_par_result_fields.html.erb
<div class="nested-fields">

	  <%= f.input :par_version, label:"PAR Version Name" %>	
	  <%= f.input :incremental_cartons %>
	  <%= f.input :spend %>
  	  <%= f.input :lift_percent %>
  	  <%= f.input :incremental_margin %>
  	  <%= f.input :roi %>
  	  <%= f.input :overall_score %>
  	  <%= f.input :comments %>
  	  <%= f.input :par_link %>
<%= link_to_remove_association "Remove PAR", f %>

</div>

app/views/forms/_program_task_fields.html.erb
<div class="nested-fields">


  <%= link_to_remove_association "Remove Program Tasks", f %>
</div>

app/views/forms/_program_type_fields.html.erb
<div class="nested-fields">


<%= f.input :name, input_html: {class: 'span7'}, label: 'Program Type'  %>
<%= f.input :task, input_html: {style: 'height:300px;', class: 'span7'}, as: :text  %>
<%= link_to_remove_association "Remove Program Type", f %> 


</div>

  

app/views/forms/edit.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/forms/index.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:sox_number) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:end_at) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
     <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= link_to form.sox_number, edit_form_path(form) %></td>
        <td><%= link_to form.name,  form_path(form)   %></td>
        <td><%= form.start_at %></td>
        <td><%= form.end_at %></td>
        <td><%= form.status %></td>
       <td><%=l form.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_form_path(form), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      form_path(form),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_form_path,
            :class => 'btn btn-primary' %>

app/views/forms/new.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/forms/show.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%= @form.sox_number %> <%= @form.name %></h1>
</div>

<dl class="dl-horizontal">

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              forms_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_form_path(@form), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              form_path(@form),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Soxform" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/calendar">Soxform</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Program List", "/forms"  %></li>
              <li><%= link_to "Create New SOX", "/forms/new"  %></li>
              <li><%= link_to "Calendar", "/calendar"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
             <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>

        </div><!--/row-->

      <footer>
        <p>&copy; BoEyC 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>